### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by alexbrunops** [bianjiang/tweetf0rm#10]
Hello everyone, I'm new here and I have a lot of questions.
It could be a little stupid, but I'm really stuck on this.

First, I'm trying to run the command `$ ./bootstrap.sh -c config.json -p proxies.json` but I get this error

> ImportError: No module named futures

I don't know why, but the others commands can run, but there is no output to say if it works or not.

Next, where the data (from the twitter) will be saved? This is my config.json file

> {
	"apikeys": {
		"i0mf0rmer01" :{
			"app_key":"xYtnU1e4bvFNxoLYVdasBsAUPjkO",
			"app_secret":"hTvAgGP83R3Z23ktFnabqxiUm2vkRkRStQcpzYm9MblzwFYD0kaI",
			"oauth_token":"45737364-FhIYhGKmaWcIPjJLvutonrmjlFszykdgngrmNIObH6",
			"oauth_token_secret":"7PcktvTDvQU37h1jYZEYJcjYFveanBBb33SQ5IkZYhGINX"
		}
	},
	"redis_config": {
		"host": "localhost",
		"port": 6379,
		"db": 0
	},
	"verbose": "True",
	"output": "./data",
	"archive_output": "./data"
}

There is no 'data' folder after I run a simple command like `client.sh -c config.json -cmd CRAWL_FRIENDS -d 1 -dt "ids" -uid 45737364`.

Thanks in advanced.

**Comment by bianjiang** [comment]
ImportError: No module named futures

You need to resolve this first. 

Install futures with

pip install futures

**Comment by alexbrunops** [comment]
I already did this.

**Comment by bianjiang** [comment]
Then it's not installed correctly. Python 2.7? 

Run python, post the version number; then run `import futures` on the interactive command line to see if you get errors. If you do, then it's something with your python installation.

**Comment by alexbrunops** [comment]
Yes, Python 2.7.
Still the error on the interactive command line.

**Comment by bianjiang** [comment]
Repull, just updated, new futures package changed from 

import futures 

to 

import concurrent.futures
