### ISSUE TITLE
 no crawler is alive... waiting to recreate all crawlers

### ISSUE THREAD

**Issue by bakhooleh** [bianjiang/tweetf0rm#12]
Hi ,
i am using tweetf0rm crawler to get data from twitter for my thesis , i followed all the instructions and installed them but i got this error :  """ no crawler is alive... waiting to recreate all crawlers "" , it seems like the proxies that listed in the proxy.json doesn't work for me . so i decided to ask help from you , what should i do ? are there any other proxies or any suggestion to solve this problem?

**Comment by bianjiang** [comment]
You'll need to find your own proxies.  The proxies in the list are rather just examples.  Note, you don't need proxy to crawl data.  You just can't crawl a lot without proxies.  Preferably, you will want to get private proxies.
