### ISSUE TITLE
I messed up.

### ISSUE THREAD

**Issue by Myst1cV3ct0r** [bianjiang/tweetf0rm#13]
sudo ./bootstrap.sh  -c config_sample.json 
INFO-[2017-03-04 22:38:57,578][bootstrap][start_server][99]: output to /home/kaz/twitsearch/Twitcrawl/tweetf0rm/data
INFO-[2017-03-04 22:38:57,578][bootstrap][start_server][100]: archived to /home/kaz/twitsearch/Twitcrawl/tweetf0rm/data/archived
INFO-[2017-03-04 22:38:57,854][scheduler][__init__][46]: number of crawlers: 1
INFO-[2017-03-04 22:38:57,855][twitter_api][__init__][26]: {'apikeys': {u'oauth_token_secret': u'ACCESS_TOKEN_SECRET', u'app_secret': u'CONSUMER_SECRET', u'oauth_token': u'ACCESS_TOKEN', u'app_key': u'CONSUMER_KEY'}, 'client_args': {'timeout': 300}}
ERROR-[2017-03-04 22:38:58,029][scheduler][__init__][56]: Unable to obtain OAuth 2 access token.
INFO-[2017-03-04 22:38:58,031][scheduler][__init__][63]: number of crawlers: 1 created
INFO-[2017-03-04 22:38:58,033][bootstrap][start_server][108]: starting node_id: 29349c7140248a452d5e090704245570
INFO-[2017-03-04 22:38:58,035][bootstrap][start_server][142]: no crawler is alive... waiting to recreate all crawlers...
^[[A^[[BINFO-[2017-03-04 22:40:58,135][bootstrap][start_server][122]: []
INFO-[2017-03-04 22:40:58,135][bootstrap][start_server][142]: no crawler is alive... waiting to recreate all crawlers...

"Unable to obtain OAuth2 Token"

I think I gave it the wrong keys from twitter but I double checked everything and made sure that these keys worked I don't want to use a proxy but I am pretty sure that I have to use at least one proxy.

Let me know what I am doing wrong here.

**Comment by bianjiang** [comment]
1) You don't need a proxy.  It will just use your local connection, if you don't config proxy at all.

2) It is OAUTH error, which means auth with Twitter failed. 

INFO-[2017-03-04 22:38:57,855][twitter_api][init][26]: {'apikeys': {u'oauth_token_secret': u'ACCESS_TOKEN_SECRET', u'app_secret': u'CONSUMER_SECRET', u'oauth_token': u'ACCESS_TOKEN', u'app_key': u'CONSUMER_KEY'}, 'client_args': {'timeout': 300}}

Did you replace you real keys with u'CONSUMER_KEY', u'CONSUMER_SECRET', etc before upload the comment or are these the real values?

**Comment by Myst1cV3ct0r** [comment]
Yeah, no matter what values I put into it it always gives that error I'll post a screen shot or some code in a bit.
