### ISSUE TITLE
The output folder is empty after I run the codes(no error occurs)

### ISSUE THREAD

**Issue by thenewcomer** [bianjiang/tweetf0rm#14]
Hi~
I am trying to use your code to collect data from twitter. But after I have followed all the steps and strat to run  ./bootstrap.sh -c config.json  without proxies, the output folder is always emputy and I still can not collect any data. I don't know which part is going wrong, hope you can help me. My platform is Macbook and my python version is 2.7, here are the messages from terminal:
➜  tweetf0rm-master **./bootstrap.sh -c config.json**                
INFO-[2017-03-23 16:56:20,127][bootstrap][start_server][99]: output to /Users/xiangyuanxin/Developer/collectTwitterData/data
INFO-[2017-03-23 16:56:20,128][bootstrap][start_server][100]: archived to /Users/xiangyuanxin/Developer/collectTwitterData/data/archived
INFO-[2017-03-23 16:56:21,037][scheduler][__init__][46]: number of crawlers: 1
INFO-[2017-03-23 16:56:21,040][twitter_api][__init__][26]: {'apikeys': {u'oauth_token_secret': u'jT4RL4a11zT4Zyb4icbEc1dp5rr3odrtVoeyNV1****', u'app_secret': u'oMbssGKczQxkXgs34z9Tus6wRebkfK5qBSg7AD0Bv2q5o****', u'oauth_token': u'783543426411294720-XSyiiaxAuY5723pGT3GRSujTAPIthPR', u'app_key': u'mcqIwVZq4xwi6vWw9oSuW1G9y'}, **'client_args': {'timeout': 300}**}
INFO-[2017-03-23 16:56:22,474][scheduler][__init__][63]: number of crawlers: 1 created
INFO-[2017-03-23 16:56:22,475][bootstrap][start_server][108]: starting node_id: b54b5c1ecdff3f6f8cadefe4f28bae7c
INFO-[2017-03-23 17:02:22,524][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:08:22,546][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:14:22,589][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:20:22,634][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:26:22,702][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:26:22,704][scheduler][balancing_load][128]: crawler with max_qsize: mcqIwVZq4xwi6vWw9oSuW1G9y (0)
INFO-[2017-03-23 17:26:22,704][scheduler][balancing_load][129]: crawler with min_qsize: mcqIwVZq4xwi6vWw9oSuW1G9y (0)
INFO-[2017-03-23 17:26:22,704][scheduler][balancing_load][130]: max_qsize - min_qsize > 0.5 * min_qsize ?: False
INFO-[2017-03-23 17:32:22,863][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:38:23,006][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]
INFO-[2017-03-23 17:44:23,161][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': u'mcqIwVZq4xwi6vWw9oSuW1G9y',
  'crawler_queue_key': u'queue:b54b5c1ecdff3f6f8cadefe4f28bae7c:mcqIwVZq4xwi6vWw9oSuW1G9y',
  'qsize': 0}]

**Comment by bianjiang** [comment]
Did you send in a command from the client script?

**Comment by be-thinking** [comment]
Hi, I faced the same problem.
And I pushed some commands by client script.
But no data has collected.
Was anything wrong with my setup?

Follow is my setup and result.

Config File:
{
	"apikeys": {
		"i0mf0rmer01" :{
			"app_key":"xxxx",
			"app_secret":"xxxx",
			"oauth_token":"xxxx-xxxx",
			"oauth_token_secret":"xxxx"
		}
	},
	"redis_config": {
		"host": "localhost",
		"port": 6379,
		"db": 0,
		"password": "1xxxx4"
	},
	"verbose": "True",
	"output": "/mnt/redis/twitter/data",
	"archive_output": "/mnt/redis/twitter/data"
}

Command list in Redis:
127.0.0.1:6379> lrange queue:3f75cd69df8ddf8f33e8f8d6f48375cf 0 100
1) "{\"user_id\": \"147163321\", \"data_type\": \"ids\", \"cmd\": \"CRAWL_FOLLOWERS\", \"bucket\": \"follower_ids\", \"depth\": \"1\", \"cmd_hash\": \"2e14d164907982cf8ae41a362a6bb716\"}"
2) "{\"user_id\": \"147163321\", \"data_type\": \"ids\", \"cmd\": \"CRAWL_FOLLOWERS\", \"bucket\": \"follower_ids\", \"depth\": \"1\", \"cmd_hash\": \"2e14d164907982cf8ae41a362a6bb716\"}"

And when I executed command like:
./bootstrap.sh -c config.json

The output was:
INFO-[2017-08-17 15:42:38,732][bootstrap][start_server][99]: output to /mnt/redis/twitter/data
INFO-[2017-08-17 15:42:38,732][bootstrap][start_server][100]: archived to /mnt/redis/twitter/data/archived
INFO-[2017-08-17 15:42:38,905][scheduler][__init__][46]: number of crawlers: 1
INFO-[2017-08-17 15:42:38,907][twitter_api][__init__][26]: {'apikeys': {u'oauth_token_secret': u'xxxx', u'app_secret': xxxx', u'oauth_token': u'xxxx-xxxxx', u'app_key': xxxxx'}, 'client_args': {'timeout': 300}}
INFO-[2017-08-17 15:42:38,970][scheduler][__init__][63]: number of crawlers: 1 created
INFO-[2017-08-17 15:42:38,970][bootstrap][start_server][108]: starting node_id: 3f75cd69df8ddf8f33e8f8d6f48375cf
INFO-[2017-08-17 15:48:39,135][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': xxxx',
  'crawler_queue_key': u'queue:3f75cd69df8ddf8f33e8f8d6f48375cf:xxxx',
  'qsize': 0}]
INFO-[2017-08-17 15:54:39,218][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': xxxxx',
  'crawler_queue_key': u'queue:3f75cd69df8ddf8f33e8f8d6f48375cf:txxxx',
  'qsize': 0}]
INFO-[2017-08-17 16:00:39,307][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': xxxx',
  'crawler_queue_key': u'queue:3f75cd69df8ddf8f33e8f8d6f48375cf:txxxx',
  'qsize': 0}]
INFO-[2017-08-17 16:06:39,495][bootstrap][start_server][122]: [{'alive?': True,
  'crawler_id': xxxxx',
  'crawler_queue_key': u'queue:3f75cd69df8ddf8f33e8f8d6f48375cf:txxxx',
  'qsize': 0}]

And nothing outputed to data folder.

**Comment by bianjiang** [comment]
You need to send a command to the server through the client script.  Did you do that?

**Comment by be-thinking** [comment]
Does the command you said like
"./client.sh -c config.json -cmd CRAWL_FOLLOWERS -d 1 -dt "ids" -uid 147163321" ?

Yes, I executed it before running "./bootstrap.sh -c config.json".

**Comment by bianjiang** [comment]
The command is sent to the server.  So you should run the server first (the second part)

**Comment by be-thinking** [comment]
Thank you for your reply very much.
It works!
