### ISSUE TITLE
"Rate limit reached" displayed, but it remained actually.

### ISSUE THREAD

**Issue by chrono-k** [bianjiang/tweetf0rm#16]
Hi, 
I faced a new problem.
Cloud you tell me how to find the reason and resolve it？

I executed server and sent a command to get followers as following
"./client.sh -c config.json -cmd CRAWL_FOLLOWERS -d 1 -dt "ids" -uid 147163321".

Then the next message displayed by the console of the server.
WARNING-[2017-08-17 21:51:50,514][twitter_api][rate_limit_error_occured][61]: [{u'application': u'xxxx'}] rate limit reached, sleep for 803.

But when I checked the rate limit from twitter API( application/rate_limit_status)，
it is shown that the rate limit did not reach.
(Actually, the result shows that all of APIs have not been invoked except 'rate_limit_status')
Next is the result from API.
....
         'application':{  
            '/application/rate_limit_status':{  
               'limit':180,
               'remaining':179,
               'reset':1502978445
            }
         },
....
         'followers':{  
            '/followers/ids':{  
               'limit':15,
               'remaining':15,
               'reset':1502978445
            },
            '/followers/list':{  
               'limit':15,
               'remaining':15,   <----- the api did not be invoked.
               'reset':1502978445
            }
         },

Thank you very much.

**Comment by bianjiang** [comment]
@chrono-k If you still need a solution, email me.
