### ISSUE TITLE
ModuleNotFoundError: No module named 'twython'

### ISSUE THREAD

**Issue by p4pupro** [bianjiang/tweetf0rm#18]
Hi, 

I am getting this error...

File "twitter_streamer.py", line 24, in <module>
    import twython
ModuleNotFoundError: No module named 'twython'

But I have install twython ...  -> pip install twython   -> right install...

And on the class twitter_streamer.py twython is right imported...
     import twython
     from util import full_stack, chunks, md5
     class TwitterStreamer(twython.TwythonStreamer):

Can someone help me please ?

**Comment by bianjiang** [comment]
Wrong version of python

**Comment by estathop** [comment]
you need pip3 for python 3
