### ISSUE TITLE
Error on console, program does not collapse

### ISSUE THREAD

**Issue by estathop** [bianjiang/tweetf0rm#20]
Greeting again, I configured all the necessary files according to my needs but in the console the line below appears but the program does not collapse and continues to fetch tweets but my search words are in catalan and for about 2 hours it fetched nothing, so I want to know if I did something wrong or the are not any tweets at all.
Console Error:
`(2019-06-06 12:03:42,765) [22347] ERROR: exception: file() takes at most 3 arguments (4 given)`

**Comment by bianjiang** [comment]
What’s your config and what’s the command line you used?

**Comment by estathop** [comment]
`python twitter_tracker.py -c /home/estathop/tweetf0rm/config.json -cmd search -o /home/estathop/tweetf0rm/data/search_query -cc /home/estathop/tweetf0rm/test_data/search.json -wait 5`

After searching around about this particular error it is an inconsistency between python 2& 3, so when I switched to python3 the program executed normally, without errors, it fetched many MBs of data where it should but there is not much going on in the console.

**Comment by estathop** [comment]
In this block

```
{
        "apikeys": {
                "i0mf0rmer01": {
                        "app_key": "APP_KEY",
                        "app_secret": "APP_SECRET",
                        "oauth_token": "OAUTH_TOKEN",
                        "oauth_token_secret": "OAUTH_TOKEN_SECRET"
                }
        }
}
```
what is `i0mf0rmer01` supposed to be ? the username of the dev or the name of the app ?

**Comment by bianjiang** [comment]
That doesn’t matter, as long as you have the right APP KEY, etc.



Jiang

On Jun 6, 2019, at 18:24, estathop <notifications@github.com<mailto:notifications@github.com>> wrote:


In this block

{
        "apikeys": {
                "i0mf0rmer01": {
                        "app_key": "APP_KEY",
                        "app_secret": "APP_SECRET",
                        "oauth_token": "OAUTH_TOKEN",
                        "oauth_token_secret": "OAUTH_TOKEN_SECRET"
                }
        }
}


what is i0mf0rmer01 supposed to be ? the username of the dev or the name of the app ?

**Comment by estathop** [comment]
(API key) is APP_KEY
(API secret key) is APP_SECRET
(Access token) is OAUTH_TOKEN
(Access token secret) is OAUTH_TOKEN_SECRET

Do I stand correct ?

**Comment by bianjiang** [comment]
Yes

Jiang

On Jun 6, 2019, at 18:32, estathop <notifications@github.com<mailto:notifications@github.com>> wrote:


(API key) is APP_KEY
(API secret key) is APP_SECRET
(Access token) is OAUTH_TOKEN
(Access token secret) is OAUTH_TOKEN_SECRET

Do I stand correct ?

**Comment by bianjiang** [comment]
Python 3 only.  So it did or it did not fetch any data?  Your comment wasn’t consistent

**Comment by estathop** [comment]
Python 2 didn't fetch any data, it showed the error and a message with 0 tweets fetched, and did not even create a json file

`python3 twitter_tracker.py -c /home/estathop/tweetf0rm/config.json -cmd search -o /home/estathop/tweetf0rm/data/search_query -cc /home/estathop/tweetf0rm/test_data/search.json -wait 5`

works like a charm and is still working. Maybe it should be clarified that tweetf0rm is built upon python 3
