### ISSUE TITLE
Retweets in JSON are cut

### ISSUE THREAD

**Issue by estathop** [bianjiang/tweetf0rm#22]
While using the search/tweets command the texts of tweets in JSON retrieved that are REtweets are cut. They start with the letters RT. Do you know why this is happening ?
For example, 

'RT @elpais_cultura: Michel Ocelot: "Soy consciente de la responsabilidad moral que conlleva dirigir una película. Por eso hasta en mi estét…'

**Comment by bianjiang** [comment]
Default behavior of Twitter API, check Twitter API docs please



Jiang

On Jun 26, 2019, at 15:58, estathop <notifications@github.com<mailto:notifications@github.com>> wrote:


While using the search/tweets command the texts of tweets in JSON retrieved that are REtweets are cut. They start with the letters RT. Do you know why this is happening ?
For example,

'RT @elpais_cultura: Michel Ocelot: "Soy consciente de la responsabilidad moral que conlleva dirigir una película. Por eso hasta en mi estét…'

**Comment by estathop** [comment]
can it be changed somehow in your code to fetch the complete context of the text though ?

**Comment by estathop** [comment]
after a little research I found out that you need to pass `tweet_mode='extended'` when calling the api , do you know where this should be done ? I am still searching your code @bianjiang

**Comment by estathop** [comment]
in line `315` in `twitter_crawler.py` you perform this `tweet_mode='extended'` so why is this happening ? From what I am reading, you get the full text without being truncated at ['retweeted_status']['full_text'] . Do I stand correct ?
