### ISSUE TITLE
from tweetf0rmer.user_farm import UserFarm?

### ISSUE THREAD

**Issue by stepmr** [bianjiang/tweetf0rm#5]
Hi there,
Are the scripts in /scripts/v1 supposed to be functional?  twitter_crawler.py imports UserFarm which doesn't seem to exist in the project....

Thanks for the awesome work :)

**Comment by bianjiang** [comment]
Nah, those were very old versions... I just didn't delete them. I'll keep this open reminding me to clean those up. Thanks!

**Comment by stepmr** [comment]
Ahh ok, is there a intended workflow for accomplish the same thing?   At first glance, it would seem like this would done through a couple of commands.... CRAWL_FRIENDS -> manually combine user IDs -> BATCH_CRAWL_USER_TIMELINE -> manually combine tweet IDs -> BATCH_CRAWL_TWEET

**Comment by bianjiang** [comment]
There is not a set workflow, and you are right, it will be a bunch of separate steps. The reason is that, sometime people need to create a social network (who follows who, who friends who) without getting the actual tweets. But certainly providing a predefined workflow will be nice...

**Comment by stepmr** [comment]
Right, ok that makes sense.  :beer:
