### ISSUE TITLE
Feature Request: More handlers

### ISSUE THREAD

**Issue by stepmr** [bianjiang/tweetf0rm#6]
Firstly, thanks so much for sharing your work. Secondly, in the spirit of your "I would be happy to take requests to add specific functionalities" note, it would be really helpful to have some more handlers :) I see there's a stub for Mongodb (mongodb_handler.py)... and an SQL centric one (SQLAlchemy?) could be helpful too.

**Comment by bianjiang** [comment]
Not enough use cases (for myself) to implement this at this stage. Would be happy to take contributed code on these.
