### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by 5mark** [bianjiang/tweetf0rm#7]
Hi,
first of all thank you very much for sharing your work here. I am just trying to get started with tweetf0rm. I ran into an error when trying to start form. Below I have posted the output from the terminal.
I should add that I am not very familiar with using python or the terminal.

>Marks-MBP:tweetf0rm markheuer$ ./bootstrap.sh -c config.json -p proxies.json
>Traceback (most recent call last):
> File "./tweetf0rm/bootstrap.py", line 170, in <module> config = json.load(config_f)	
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load    **kw)
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads return _default_decoder.decode(s)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()
>File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode obj, end = self.scan_once(s, idx)
> ValueError: Expecting property name: line 3 column 3 (char 18)

I am working on OSX with Python 2.7 
Further, I am still not sure how to pass a command to tweetf0rm, once it is running.

Thanks for your help!

**Comment by bianjiang** [comment]
Looks like there is something wrong with your config file. Something about it's not formatted correctly.

Would you mind paste it here? Of course get rid of the sensitive information.

You'll have to look at the client code, there are some help text there for what command to use.

**Comment by 5mark** [comment]
hi, thanks for getting in touch. For the start, I made hardly any changes to the config. Here is my config:
{
	"apikeys": {
		„copcrawler“ :{
			"app_key":"YNISfRWzhSzUZ9UlNwJg",
			"app_secret":"47531y3p5GNAPnGHW2b3Zt4SH4HKdK5Y3D14NWu4",
			"oauth_token":"91847296-sGDj0GK4v7rVJTEFQx2hW9RYHGwjVKrty7hDMkv1Q",
			"oauth_token_secret":"9UbxCTMBSQB9E9xF4xaqWGJDe88BxCpeLQG03ASomiceP"
		},
	},
	"redis_config": {
		"host": "localhost",
		"port": 6379,
		"db": 0,
		"password": ""
	},
	"verbose": "True",
	"output": „./crawldataoutput“,
	"archive_output": "./crawldatacompressed“
}

**Comment by bianjiang** [comment]
Ok, I don't know if it's formatting issue when you pasted into Markdown, but a few of them suppose to be double quotes, but showed up here as „ , which isn't valid for json file. You can validate your json file here http://jsonlint.com/. If it's not valid, then there is something wrong with your json.

Also, I did notice you have `"password": ""`, if you don't have a password, I think you can get rid of that line all together, otherwise, it will try AUTH with an empty password with redis.

**Comment by 5mark** [comment]
Thanks! You were right, I guess i messed up the formating when I used the OSX text editor to modify the config.json. Could not have faound put without your help! Thanks again for your quick support. I guess this thread can be deleted now, since it won't be helpful for anyone else.
