### ISSUE TITLE
Processing Data

### ISSUE THREAD

**Issue by 5mark** [bianjiang/tweetf0rm#8]
Hi,
I was wondering how other users processs the data generated with tweetf0rm. Since I need the data in some kind of spreadsheet format, I was going to use open refine to import he JSON file containing the tweets I crawled. The issue here is that I can only import one of the nodes from every tweet, and not all of them. e.g. the tweet might look like this:
> { 
> text: (...)
> retweeted status: {...}
> retweeted : {...}
>(...)
> }
open refine is only able to extract one of these nodes at a time, (e.g. ‘retweeted status: { (...) }' but not 'text: (...)'.

Another method I tried is to use a script for google spreadsheets called "=importJSON()", but without success.  

I further noticed that both methods work fine with a JSON file i pulled "directly from the twitter API, but I have not been able to find out what exactly the the difference was between the two JSON files. If you care to have a look at this other file, you can find it here: https://www.dropbox.com/s/detv4ttvlsgbtz0/cop21.11.1301_07.txt?dl=0

Anyway, I was wondering If any other users have experience with convertinf the tweetform data into spreadsheet format, and what your workflow is. 

best, Mark

Information on using open refine with twitter data can be found here: http://blog.ouseful.info/2012/10/02/grabbing-twitter-search-results-into-google-refine-and-exporting-conversations-into-gephi/
Information on the google spreadsheets extension can be found here: https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a

**Comment by bianjiang** [comment]
The result from tweetf0rm is just the aggregated raw json data from the  Twitter API.
Each line is a valid json, however, the entire file won't be. 

People normally write their own scripts (in whatever language they do) to process the raw data in tweetf0rm then transform to whatever format they need. 

I do the same, I have a general process ingesting the aggregated raw data, pick out the fields I need, process it (e.g., clean text, geocoding, etc.), and spill it out into csv (or keep it in json).

In Python, it's fairly easy:

```python
    
    fieldnames = ['id', 'created_at', 'text', 'location', 'city', 'state', 'uid', 'friends_count',  'followers_count', 'user_created_at', 'statuses_count']

    with open(raw_json_file, 'r') as f, open(output_file, 'a', newline='') as out:
        
        writer = csv.DictWriter(
                        out, fieldnames=fieldnames, delimiter=',', quoting=csv.QUOTE_ALL)
        writer.writeheader()

        for line in f:
            tweet = json.loads(line)
            user = tweet['user']
            output = {
                'text': tweet['text'],
                'city': xxx,
                'state': xxx,
                'id': tweet['id'],
                'location': user['location'],
                'created_at': tweet['created_at'],
                'uid': user['id'],
                'friends_count': user['friends_count'],
                'followers_count': user['followers_count'],
                'user_created_at': user['created_at'],
                'statuses_count': user['statuses_count']
            }
            
            writer.writerow(output)
```

**Comment by 5mark** [comment]
cool, thanks! I had to adapt it a little because with my python version the csv package does not handle utf-8, but now it works fine.

cheers
